import localFont from 'next/font/local';
import "./globals.css";
import CustomCursor from "@/src/components/CustomerCursor";

const myFont = localFont({
  src: '../public/fonts/next.woff2',
  variable: '--font-my-custom',
});

export const metadata = {
  title: "Jaideep N's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/photo.png" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/photo.png" />
      </head>
      <body className={`${myFont.variable} antialiased`}>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
